# Generated by Django 2.1.2 on 2018-10-13 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=200, verbose_name='Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='When')),
            ],
        ),
        migrations.CreateModel(
            name='OneOffExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.Expense')),
            ],
            bases=('expenses.expense',),
        ),
        migrations.CreateModel(
            name='PeriodicExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.Expense')),
                ('frequency', models.FloatField(verbose_name='Frequency')),
            ],
            bases=('expenses.expense',),
        ),
        migrations.AddField(
            model_name='update',
            name='expense',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.Expense'),
        ),
    ]
