# Generated by Django 2.1.3 on 2018-11-30 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('periodic', models.BooleanField(default=False, verbose_name='Periodic')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='When')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('concept', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.Concept')),
            ],
        ),
    ]
