# Generated by Django 2.1.2 on 2018-10-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='periodicexpense',
            name='frequency',
            field=models.FloatField(default=30.0, verbose_name='Frequency'),
        ),
    ]
