# Generated by Django 2.1.3 on 2018-12-24 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20181203_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='comment',
            field=models.CharField(default=' ', max_length=500, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.Group'),
        ),
    ]
