# Generated by Django 2.1.2 on 2018-10-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20181013_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='amount',
        ),
        migrations.AddField(
            model_name='update',
            name='sum',
            field=models.FloatField(default=0.0, verbose_name='Sum'),
        ),
    ]
