# Generated by Django 2.1.2 on 2018-10-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20181013_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='SporadicExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.Expense')),
            ],
            bases=('expenses.expense',),
        ),
    ]
