# Generated by Django 2.1.7 on 2019-03-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20181224_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='comment',
            field=models.CharField(blank=True, default='-', max_length=500, verbose_name='Comment'),
        ),
    ]
