# Generated by Django 2.1.2 on 2018-10-14 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_sporadicexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=200, verbose_name='Concept')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='When')),
                ('sum', models.FloatField(default=0.0, verbose_name='Sum')),
            ],
        ),
        migrations.CreateModel(
            name='OneOffIncome',
            fields=[
                ('income_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.Income')),
            ],
            bases=('expenses.income',),
        ),
        migrations.CreateModel(
            name='PeriodicIncome',
            fields=[
                ('income_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.Income')),
                ('frequency', models.FloatField(default=30.0, verbose_name='Frequency')),
            ],
            bases=('expenses.income',),
        ),
        migrations.CreateModel(
            name='SporadicIncome',
            fields=[
                ('income_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.Income')),
            ],
            bases=('expenses.income',),
        ),
        migrations.AddField(
            model_name='incomeupdate',
            name='income',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.Income'),
        ),
    ]
