# Generated by Django 2.1.7 on 2019-04-09 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20190301_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOffUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='When')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('comment', models.CharField(blank=True, default='-', max_length=500, verbose_name='Comment')),
            ],
        ),
    ]
