# Generated by Django 2.1.7 on 2019-04-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_oneoffupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='OldUpdate',
        ),
    ]
