# Generated by Django 2.1.7 on 2019-04-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20190411_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OneOffUpdate',
            new_name='OldOneOffUpdate',
        ),
    ]
