# Generated by Django 2.1.7 on 2019-04-11 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20190411_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='When')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('comment', models.CharField(blank=True, default='-', max_length=500, verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicUpdate',
            fields=[
                ('update_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.Update')),
                ('concept', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.Concept')),
            ],
            bases=('expenses.update',),
        ),
    ]
