# Generated by Django 2.1.7 on 2019-04-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_periodicupdate_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldupdate',
            name='concept',
        ),
        migrations.DeleteModel(
            name='OldUpdate',
        ),
    ]
