# Generated by Django 2.1.7 on 2019-04-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_oneoffupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('concept_name', models.CharField(max_length=100, verbose_name='Concept name')),
            ],
        ),
        migrations.DeleteModel(
            name='OldOneOffUpdate',
        ),
    ]
