# Generated by Django 2.1.7 on 2019-04-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_auto_20190411_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptiontranslation',
            name='concept',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.Concept'),
        ),
    ]
