# Generated by Django 2.1.7 on 2019-04-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_remove_descriptiontranslation_concept_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=250, verbose_name='Line')),
            ],
        ),
    ]
