# Generated by Django 2.1.7 on 2019-04-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_parsedlines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParsedLines',
            new_name='ParsedLine',
        ),
    ]
